global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'API-GATEWAY'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'AUTH-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9000'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'DISCOVERY-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'BOOKING-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9030' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'PROFILE-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9020' ] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'NOTIFICATION-SERVICE'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:9010' ] ## only for demo purposes don't use host.docker.internal in production