server:
  port: 9000

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://${LOCAL_HOST:localhost}:5432/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${LOCAL_HOST:localhost}:8761/eureka


jwt:
  secret: f7e4feb04b5931273685ec897831a2cd44da8ba567756e09b825cf93847ff001
  expiration: 60000
#  expiration: 300000
