server:
  port: 9000

spring:
  profiles:
    active: kafka
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://${DOCKER_HOST:localhost}:5432/user_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jms:
    pub-sub-domain: true
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis

kafka:
  host: ${KAFKA_HOST:localhost:9092}

eureka:
  instance:
    hostname: ${DOCKER_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${DOCKER_HOST:localhost}:8761/eureka

jwt:
  secret: f7e4feb04b5931273685ec897831a2cd44da8ba567756e09b825cf93847ff001
  expiration: 900000

registration:
  validation:
    password-pattern: ^(?=.*\d)(?=.*[A-Z])(?=.*[a-z]).{8,}$

queue-name:
    user-activation: user.activation.queue
    user-forgot-password: user.forgot.password.queue

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${DOCKER_HOST:localhost}:9411/api/v2/spans