server:
  port: 9010

logging:
  level:
    org.springframework.jms: DEBUG

eureka:
  instance:
    hostname: ${DOCKER_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${DOCKER_HOST:localhost}:8761/eureka

spring:
  profiles:
    active: kafka
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: ${MAILDEV_HOST:localhost}
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
            starttls:
              enable: true
            connectiontimeout: 5000
            timout: 3000
            writetimeout: 5000
  jms:
    pub-sub-domain: true
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: NOTIFICATION-SERVICE-1
      properties:
        spring:
          json:
            trusted:
              packages: '*'
      auto-offset-reset: earliest

email:
  enabled: true
  user:
    activation-link: http://localhost:4200/activate-account?token=%s
    forgot-password-link: http://localhost:4200/reset-password?token=%s

queue-name:
  user-activation: user.activation.queue
  user-forgot-password: user.forgot.password.queue

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${DOCKER_HOST:localhost}:9411/api/v2/spans