eureka:
  instance:
    hostname: ${DOCKER_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${DOCKER_HOST:localhost}:8761/eureka

server:
  port: 8080

jwt:
  secret: f7e4feb04b5931273685ec897831a2cd44da8ba567756e09b825cf93847ff001
  expiration: 86400

spring:
  application:
    name: API-GATEWAY
  profiles:
    active: development
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH


management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${DOCKER_HOST:localhost}:9411/api/v2/spans