server:
  port: 9030

eureka:
  instance:
    hostname: ${LOCAL_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${LOCAL_HOST:localhost}:8761/eureka

spring:
  application:
    name: BOOKING-SERVICE
  data:
    mongodb:
      host: ${LOCAL_HOST:localhost}
      port: 27017
      database: bookings

auth-service:
  url: http://AUTH-SERVICE

logging:
  level:
    org.hibernate.SQL: INFO

jwt:
  secret: f7e4feb04b5931273685ec897831a2cd44da8ba567756e09b825cf93847ff001
  expiration: 300000