server:
  port: 9040

eureka:
  instance:
    hostname: ${DOCKER_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${DOCKER_HOST:localhost}:8761/eureka

spring:
  application:
    name: PRODUCTS
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://${DOCKER_HOST:localhost}:5432/health-care-parent
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

auth-service:
  url: http://AUTH-SERVICE

logging:
  level:
    org.hibernate.SQL: INFO

jwt:
  secret: f7e4feb04b5931273685ec897831a2cd44da8ba567756e09b825cf93847ff001
  expiration: 300000

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${DOCKER_HOST:localhost}:9411/api/v2/spans