server:
  port: 9020

eureka:
  instance:
    hostname: ${LOCAL_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${LOCAL_HOST:localhost}:8761/eureka

spring:
  application:
    name: PROFILE-SERVICE
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: ${LOCAL_HOST:localhost}
      port: 27017
      database: provider
#      username: I_DONT_KNOW
#      password: SOME_SECRET

#liquibase:
#  change-log: classpath:liquibase-changeLog.xml

logging:
  level:
    org.hibernate.SQL: INFO

jwt:
  secret: f7e4feb04b5931273685ec897831a2cd44da8ba567756e09b825cf93847ff001