server:
  port: 9020

eureka:
  instance:
    hostname: ${DOCKER_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${DOCKER_HOST:localhost}:8761/eureka

spring:
  application:
    name: PROFILE-SERVICE
  profiles:
    active: kafka
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      host: ${DOCKER_HOST:localhost}
      port: 27017
      database: provider
#      username: I_DONT_KNOW
#      password: SOME_SECRET

logging:
  level:
    org.hibernate.SQL: INFO

jwt:
  secret: f7e4feb04b5931273685ec897831a2cd44da8ba567756e09b825cf93847ff001

management:
  endpoints:
    web:
      exposure:
        include: "health, info, metrics, prometheus"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${DOCKER_HOST:localhost}:9411/api/v2/spans