eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#  instance:
#    prefer-ip-address: true
#    hostname: localhost

server:
  port: 8761

spring:
  application:
    name: discovery-server
